---
title: "Meta_Music"
author: "Nan Zhao"
date: "2023-12-20"
output: html_document
---

```{r global_options, warning=FALSE, message=FALSE,include=FALSE}

# package install checking 

if(!require(dplyr)){install.packages("dplyr")}
library(dplyr)
if(!require(meta)){install.packages("meta")}
library(meta)
if(!require(dmetar)){install.packages("dmetar")}
library(dmetar)

knitr::opts_chunk$set(echo = TRUE)
```



```{r}
# load data for all meta-analyses 
# Place the data set in the same folder with the .Rmd file to load data or specify the Github path

dat_sleep <- read.csv("sleep.csv")
dat_depress <- read.csv("depression.csv")
dat_anxiety <- read.csv("anxiety.csv")

```

# 1.1 Subjective sleep outcome meta-analysis
```{r}
m.sleep <- metacont(n.e=n.e,
                    mean.e=mean.e,
                    sd.e=sd.e,
                    n.c=n.c,
                    sd.c=sd.c,
                    mean.c=mean.c,
                    studlab=Author,
                    data=dat_sleep,
                    sm="SMD",
                    method.smd="Hedges",  
                    fixed=FALSE,
                    random=TRUE,
                    method.tau="REML",  
                    hakn=TRUE, # for small sample size 
                    title="Music intervention on Sleep Quality")
summary(m.sleep)
```

```{r plot_chunk1, fig.width=10, fig.height=3}
# Sleep forest plot 
forest.meta(m.sleep, 
            sortvar = TE,
            prediction = FALSE, 
            print.tau2 = FALSE,
            leftlabs = c("Author", "g", "SE"))
```

```{r}
# sleep funnel plot 

col.contour = c("gray75", "gray85", "gray95")  # color
funnel.meta(m.sleep, xlim = c(-5, 2),
            contour = c(0.9, 0.95, 0.99),
            col.contour = col.contour,
            studlab=FALSE)
legend(x = .8, y = 0.01, 
       legend = c("p < 0.1", "p < 0.05", "p < 0.01"),
       fill = col.contour)
title("Sleep Quality")
```


```{r}
# Sleep Outlier tests (Lu 2022)
m.sleep.inf <- InfluenceAnalysis(m.sleep, random=TRUE)
plot(m.sleep.inf, "influence")
```

# 1.2 Subjective sleep outcome meta-analysis without outlier (Lu 2022)
```{r}
# Delete outlier: Lu 2022
s1.dat_sleep <- dat_sleep[dat_sleep$Author != "Lu et al, 2022",]

# re-run the meta analysis (Sleep S1) 
s1.sleep <- metacont(n.e=n.e,
                    mean.e=mean.e,
                    sd.e=sd.e,
                    n.c=n.c,
                    sd.c=sd.c,
                    mean.c=mean.c,
                    studlab=Author,
                    data=s1.dat_sleep,
                    sm="SMD",
                    method.smd="Hedges",
                    fixed=FALSE,
                    random=TRUE,
                    method.tau="REML",
                    hakn=TRUE,
                    title="Music intervention on Sleep (S1)")
summary(s1.sleep)
```

```{r plot_chunk2, fig.width=10, fig.height=2.5}
# s1 sleep forest plot
forest.meta(s1.sleep, 
            sortvar = TE,
            prediction = FALSE, 
            print.tau2 = FALSE,
            leftlabs = c("Author", "g", "SE"))
```

```{r}
# s1 sleep funnel plot without the outlier 

col.contour = c("gray75", "gray85", "gray95")  # color
funnel.meta(s1.sleep, xlim = c(-5, 2),
            contour = c(0.9, 0.95, 0.99),
            col.contour = col.contour,
            studlab=FALSE)
legend(x = .8, y = 0.01, 
       legend = c("p < 0.1", "p < 0.05", "p < 0.01"),
       fill = col.contour)
title("Sleep Quality Without Outliers")
```

# 2.1 Depression meta-analysis 
```{r}
m.depress <- metacont(n.e=n.e,
                    mean.e=mean.e,
                    sd.e=sd.e,
                    n.c=n.c,
                    sd.c=sd.c,
                    mean.c=mean.c,
                    studlab=Author,
                    data=dat_depress,
                    sm="SMD",
                    method.smd="Hedges",
                    fixed=FALSE,
                    random=TRUE,
                    method.tau="REML",
                    hakn=TRUE,
                    title="Music intervention on Depression")
summary(m.depress)
```

```{r plot_chunk3, fig.width=10, fig.height=2.5}
# Depression forest plot
forest.meta(m.depress, 
            sortvar = TE,
            prediction = FALSE, 
            print.tau2 = FALSE,
            leftlabs = c("Author", "g", "SE"))
```

```{r}
# Depression funnel plot 

col.contour = c("gray75", "gray85", "gray95")  # color
funnel.meta(m.depress, xlim = c(-5, 3),
            contour = c(0.9, 0.95, 0.99),
            col.contour = col.contour,
            studlab=FALSE)
legend(x = 1, y = 0.01, 
       legend = c("p < 0.1", "p < 0.05", "p < 0.01"),
       fill = col.contour)
title("Depression")
```

```{r}
#  Depression outliers (Yang 2021)
m.depress.inf <- InfluenceAnalysis(m.depress, random=TRUE)
plot(m.depress.inf, "influence")

```

# 2.2 Depression meta-analysis without outliers (Yang, 2O21)
```{r}
# Delete outlier: Yang 2021
s1.dat_depress <- dat_depress[dat_depress$Author != "Yang et al, 2021",]

# re-run the meta analysis (depress S1)
s1.depress <- metacont(n.e=n.e,
                    mean.e=mean.e,
                    sd.e=sd.e,
                    n.c=n.c,
                    sd.c=sd.c,
                    mean.c=mean.c,
                    studlab=Author,
                    data=s1.dat_depress,
                    sm="SMD",
                    method.smd="Hedges",
                    fixed=FALSE,
                    random=TRUE,
                    method.tau="REML",
                    hakn=TRUE,
                    title="Music intervention on Depression (Without Yang)")
summary(s1.depress)
```


```{r plot_chunk4, fig.width=10, fig.height=2.5}
# s1 depress forest plot without the outlier 
forest.meta(s1.depress, 
            sortvar = TE,
            prediction = FALSE, 
            print.tau2 = FALSE,
            leftlabs = c("Author", "g", "SE"))
```
```{r}
# s1 Depression funnel plot without the outlier 

col.contour = c("gray75", "gray85", "gray95")  # color
funnel.meta(s1.depress, xlim = c(-3, 3),
            contour = c(0.9, 0.95, 0.99),
            col.contour = col.contour,
            studlab=FALSE)
legend(x = 1, y = 0.01, 
       legend = c("p < 0.1", "p < 0.05", "p < 0.01"),
       fill = col.contour)
title("Depression Without Outliers")
```

# 3.1 Anxiety meta-analysis 
```{r}
# remove one measure for Blanaru et al (removed STAI from Blanaru et al) due to the double measures 
dat_anxiety <- dat_anxiety %>% filter(mean.e!=65.7)
```

```{r}
m.anxiety <- metacont(n.e=n.e,
                    mean.e=mean.e,
                    sd.e=sd.e,
                    n.c=n.c,
                    sd.c=sd.c,
                    mean.c=mean.c,
                    studlab=Author,
                    data=dat_anxiety,
                    sm="SMD",
                    method.smd="Hedges",
                    fixed=FALSE,
                    random=TRUE,
                    method.tau="REML",
                    hakn=TRUE,
                    title="Music intervention on Anxiety")
summary(m.anxiety)
```

```{r plot_chunk5, fig.width=10, fig.height=2.5}
# anxiety forest plot 
forest.meta(m.anxiety, 
            sortvar = TE,
            prediction = FALSE, 
            print.tau2 = FALSE,
            leftlabs = c("Author", "g", "SE"))
```
```{r}
# Anxiety funnel plot 

col.contour = c("gray75", "gray85", "gray95")  # color
funnel.meta(m.anxiety, xlim = c(-7.5, 3),
            contour = c(0.9, 0.95, 0.99),
            col.contour = col.contour,
            studlab=FALSE)
legend(x = 0.5, y = 0.01, 
       legend = c("p < 0.1", "p < 0.05", "p < 0.01"),
       fill = col.contour)
title("Anxiety")
```
```{r}
#  Anxiety  outlier tests (Yang 2021)
m.anxiety.inf <- InfluenceAnalysis(m.anxiety, random=TRUE)
plot(m.anxiety.inf, "influence")

```

# 3.2 Anxiety meta-analysis without outliers (Yang, 2O21)
```{r}
# delete the outlier (Yang, 2021)
s1.dat_anxiety <- dat_anxiety[dat_anxiety$n.e != 30,]

# s1 anxiety meta-analysis without the outlier (Yang, 2021)
s1.anxiety <- metacont(n.e=n.e,
                    mean.e=mean.e,
                    sd.e=sd.e,
                    n.c=n.c,
                    sd.c=sd.c,
                    mean.c=mean.c,
                    studlab=Author,
                    data=s1.dat_anxiety,
                    sm="SMD",
                    method.smd="Hedges",
                    fixed=FALSE,
                    random=TRUE,
                    method.tau="REML",
                    hakn=TRUE,
                    title="Music intervention on Anxiety (S1)")
summary(s1.anxiety)
```


```{r plot_chunk6, fig.width=10, fig.height=2.5}
# s1 anxiety forest plot without the outlier 
forest.meta(s1.anxiety, 
            sortvar = TE,
            prediction = FALSE, 
            print.tau2 = FALSE,
            leftlabs = c("Author", "g", "SE"))
```
```{r}
# s1 Anxiety funnel plot without the outlier  

col.contour = c("gray75", "gray85", "gray95")  # color
funnel.meta(s1.anxiety, xlim = c(-7.5, 3),
            contour = c(0.9, 0.95, 0.99),
            col.contour = col.contour,
            studlab=FALSE)
legend(x = 0.5, y = 0.01, 
       legend = c("p < 0.1", "p < 0.05", "p < 0.01"),
       fill = col.contour)
title("Anxiety Without Outliers ")
```

